# emc - Edit My Config.
# https://github.com/demartini/emc.fish

complete --command $EMC_CMD --no-files --description "Oh My Fish"
complete --command $EMC_CMD --no-files --arguments bash     --condition "__fish_use_subcommand" --description "Opens the Bash config file."
complete --command $EMC_CMD --no-files --arguments fish     --condition "__fish_use_subcommand" --description "Opens the Fish config file."
complete --command $EMC_CMD --no-files --arguments git      --condition "__fish_use_subcommand" --description "Opens the Git config file."
complete --command $EMC_CMD --no-files --arguments gpg      --condition "__fish_use_subcommand" --description "Opens the GPG config file."
complete --command $EMC_CMD --no-files --arguments gpga     --condition "__fish_use_subcommand" --description "Opens the GPG agent config file."
complete --command $EMC_CMD --no-files --arguments ssh      --condition "__fish_use_subcommand" --description "Opens the SSH config file."
complete --command $EMC_CMD --no-files --arguments nvim     --condition "__fish_use_subcommand" --description "Opens the Neovim config file."
complete --command $EMC_CMD --no-files --arguments starship --condition "__fish_use_subcommand" --description "Opens the starship config file."
complete --command $EMC_CMD --no-files --arguments tmux     --condition "__fish_use_subcommand" --description "Opens the tmux config file."
complete --command $EMC_CMD --no-files --arguments vim      --condition "__fish_use_subcommand" --description "Opens the Vim config file."
complete --command $EMC_CMD --no-files --arguments zsh      --condition "__fish_use_subcommand" --description "Opens the Zsh config file."
complete --command $EMC_CMD --no-files --arguments add      --condition "__fish_use_subcommand" --description "Add a new config file option (see README)"
complete --command $EMC_CMD --no-files --arguments remove   --condition "__fish_use_subcommand" --description "Remove a config file  option (see README)"
complete --command $EMC_CMD --no-files --arguments list     --condition "__fish_use_subcommand" --description "List all config file options"
complete --command $EMC_CMD --no-files --arguments backup   --condition "__fish_use_subcommand" --description "Backs up current config. Do before update by fisher"
complete --command $EMC_CMD --no-files --arguments restore  --condition "__fish_use_subcommand" --description "Restores backup config. Do after update by fisher"
complete --command $EMC_CMD --no-files --arguments version  --condition "__fish_use_subcommand" --description "See version"
complete --command $EMC_CMD --no-files --arguments help     --condition "__fish_use_subcommand" --description "Print this help."
